### ISSUE TITLE
need to update the interpreter in generated code to run via python3

### ISSUE THREAD

**Issue by JimZam** [OpenRoberta/robertalab-ev3dev#24]
Good evening. Finally open roberta works for me from the webbrowser :-) but now, if I try to run NEPOprog.py from the command line I get the following error and it doesn't work.
Thank you and regards

Antonio

File "NEPOprog.py", line 4, in <module>
    from roberta.ev3 import Hal

**Comment by ensonic** [comment]
I need to update the "#!/usr/bin/python", but that will need another release :/ I was hoping that the default python version is controlled via the alternatives system, but is not :/
/usr/bin/python is installed via python-minimal and python3-minimal installs /usr/bin/python3, meh.
You can just edit it manually for now.

Also you will need to run them from the FileBrowser (Brickman), otherwise it won't get switch to a new screen and your screen output and button checks won't work.

**Comment by JimZam** [comment]
Thank you ensonic. That way probably i'll be able to uninstall python-ev3dev as apt-get upgrade sugests.
Regards

**Comment by ensonic** [comment]
Yes,python-ev3dev can be removed now.
 I'll do more testing and release a new version in 1-2 weeks.

**Comment by JimZam** [comment]
Good morning Stefan. Thank you for your help.

Kind regards

 

Antonio

 

Sent: Thursday, November 10, 2016 at 9:46 PM
