### ISSUE TITLE
say block not working EV3dev

### ISSUE THREAD

**Issue by peacepro** [OpenRoberta/robertalab-ev3dev#65]
Hallo,
if I use the say block with the EV3dev-System, my robot do nothing.
Do I something wrong?
With the leJOS EV3 0.9.1-System the say block is working fine.

**Comment by ensonic** [comment]
Which version of ev3dev and the robertalab are you using. Most likely robertalab-ev3dev is not up-to-date.

**Comment by peacepro** [comment]
My EV3dev version is form 2017/09/14 and the roberta-lab is 2.7.1.

**Comment by ensonic** [comment]
Let me ask again. Did you just download an ev3dev image and use it or did you also update packages (by connecting the the ev3 via ssh and running: `sudo apt-get update; sudo apt-get upgrade`)?

I am asking since this package is now at version 1.7.4 (see https://github.com/OpenRoberta/robertalab-ev3dev/releases) and I believe you don't have the latest. We are aware that upgrading debian package is too much to ask from users and working on an alternative (see #19).

If you don't have much experience with doing updates on a linux system, I am happy to help, just let me know. The commands I quotes above will take some hours to finish, since the ev3 is quite slow and does not have much memory.

**Comment by peacepro** [comment]
Ok after i made an update & upgrade everythings works fine. 
Thank you.
Is it possible to update the OpenRoberta Wiki with 
"Connet via ssh and running: sudo apt-get update; sudo apt-get upgrade"
 https://jira.iais.fraunhofer.de/wiki/display/ORInfo/Vorbereitung+EV3+-+System+EV3dev ?

**Comment by ensonic** [comment]
awesome. I think we rather try to fix #19. But maybe we add a note into the wiki for now. I'll forward this.
